[package]
name = "nightcycle/svg-import"
description = "Creates part-based SVG models"
version = "0.1.0"
authors = ["CJ Oyer <coyer@nightcycle.us>"]
realm = "shared"
registry = "https://github.com/upliftgames/wally-index"
exclude = ["Packages", ".vscode"]

[dependencies]
math = "nightcycle/math@3.3.0"